/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.alumnogui;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author g.guzman
 */
public class AlumnoDialog extends javax.swing.JDialog {

    private AlumnoDTO dto;

    public AlumnoDTO getDto() {
        return dto;
    }

    public void setDto(AlumnoDTO dto) {
        this.dto = dto;
    }
    
    
    /**
     * Creates new form AlumnoDialog
     */
    public AlumnoDialog(java.awt.Frame parent, boolean modal, CrudOptionsEnum crudOption) {
        super(parent, modal);
        initComponents();
        this.setTitle("Diálogo");
        this.setLocationRelativeTo(null);
        
        if (crudOption==CrudOptionsEnum.READ) {
            cancelarButton.setVisible(false);
            okButton.setVisible(false);
            dniTextField.setEnabled(false);
            nombreTextField.setEnabled(false);
            apellidoTextField.setEnabled(false);
            fecNacDateChooser.setEnabled(false);
            fecIngDateChooser.setEnabled(false);
            promedioTextField.setEnabled(false);
            cantMatAprobTextField.setEnabled(false);
            estadoComboBox.setEnabled(false);
        }
        else if (crudOption==CrudOptionsEnum.UPDATE) {
            dniTextField.setEnabled(false);
        }
    }
    /**
     * Creates new form AlumnoDialog
     */
    public AlumnoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        aluPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dniTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fecIngDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        apellidoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox<>();
        jLabelFecNac = new javax.swing.JLabel();
        fecNacDateChooser = new com.toedter.calendar.JDateChooser();
        jLabelPromedio = new javax.swing.JLabel();
        promedioTextField = new javax.swing.JTextField();
        jLabelCantMat = new javax.swing.JLabel();
        cantMatAprobTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("DNI:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Fecha Ing.:");

        jLabel4.setText("Apellido");

        jLabel5.setText("Estado");

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B" }));
        estadoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoComboBoxActionPerformed(evt);
            }
        });

        jLabelFecNac.setText("Fecha Nac.:");
        jLabelPromedio.setText("Promedio:");
        jLabelCantMat.setText("Cant. Mat. Aprob.:");

        javax.swing.GroupLayout aluPanelLayout = new javax.swing.GroupLayout(aluPanel);
        aluPanel.setLayout(aluPanelLayout);
        aluPanelLayout.setHorizontalGroup(
            aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(dniTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(nombreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(apellidoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addComponent(jLabelFecNac, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(fecNacDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(fecIngDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addComponent(jLabelPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(promedioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addComponent(jLabelCantMat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(cantMatAprobTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        aluPanelLayout.setVerticalGroup(
            aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aluPanelLayout.createSequentialGroup()
                .addGroup(aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(apellidoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecNac)
                    .addComponent(fecNacDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fecIngDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPromedio)
                    .addComponent(promedioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCantMat)
                    .addComponent(cantMatAprobTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aluPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(aluPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(aluPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelarButton))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        dto = null;
        setVisible(false);
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (!validarForm()) {
            return;
        }
        dto = new AlumnoDTO();
        dto.setDni(dniTextField.getText());
        dto.setNombre(nombreTextField.getText());
        dto.setApellido(apellidoTextField.getText());

        Calendar fecNacCalendar = fecNacDateChooser.getCalendar();
        LocalDate fecNac = LocalDateTime.ofInstant(fecNacCalendar.toInstant(), fecNacCalendar.getTimeZone().toZoneId()).toLocalDate();
        dto.setFecNac(fecNac);

        Calendar calendar = fecIngDateChooser.getCalendar();
        LocalDate fecIng = LocalDateTime.ofInstant(calendar.toInstant(), calendar.getTimeZone().toZoneId()).toLocalDate();
        dto.setFecIng(fecIng);

        dto.setPromedio(promedioTextField.getText().trim());
        dto.setCantMatAprob(cantMatAprobTextField.getText().trim());

        dto.setEstado(estadoComboBox.getSelectedItem().toString().charAt(0));
        
        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println("gui.alumnogui.AlumnoDialog.formWindowOpened()");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(dto != null){
            dniTextField.setText(dto.getDni());
            nombreTextField.setText(dto.getNombre());
            if (dto.getFecNac() != null) {
                GregorianCalendar gcNac = GregorianCalendar.from(dto.getFecNac().atStartOfDay(ZoneId.systemDefault()));
                fecNacDateChooser.setCalendar(gcNac);
            }
            if (dto.getFecIng() != null) {
                GregorianCalendar gc = GregorianCalendar.from(dto.getFecIng().atStartOfDay(ZoneId.systemDefault()));
                fecIngDateChooser.setCalendar(gc);
            }
            apellidoTextField.setText(dto.getApellido());
            promedioTextField.setText(dto.getPromedio());
            cantMatAprobTextField.setText(dto.getCantMatAprob());
            estadoComboBox.setSelectedIndex(dto.getEstado() == 'A' ? 0 : 1);
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void estadoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlumnoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlumnoDialog dialog = new AlumnoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aluPanel;
    private javax.swing.JTextField apellidoTextField;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JComboBox<String> estadoComboBox;
    private com.toedter.calendar.JDateChooser fecIngDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel jLabelFecNac;
    private com.toedter.calendar.JDateChooser fecNacDateChooser;
    private javax.swing.JLabel jLabelPromedio;
    private javax.swing.JTextField promedioTextField;
    private javax.swing.JLabel jLabelCantMat;
    private javax.swing.JTextField cantMatAprobTextField;
    // End of variables declaration//GEN-END:variables

    private boolean validarForm() {
        boolean isValidForm = true;
        StringBuilder errorMessageBuilder = new StringBuilder();
        
        //dni
        String dni = dniTextField.getText();
        if(StringUtils.isBlank(dni.trim())){
            errorMessageBuilder.append("El dni no puede estar vacío\n");
            isValidForm = false;
        }
        if(dni.length() < 6 || dni.length() > 9){
            errorMessageBuilder.append("Longitud de dni inválida\n");
            isValidForm = false;
        }
        if(!StringUtils.isNumeric(dni)){
            errorMessageBuilder.append("El dni sólo puede contener números\n");
            isValidForm = false;
        }
        
        //nombre
        String nombre = nombreTextField.getText();
        if(StringUtils.isBlank(nombre.trim())){
            errorMessageBuilder.append("El nombre no puede estar vacío\n");
            isValidForm = false;
        }
        if(!StringUtils.isAlphaSpace(nombre)){
            errorMessageBuilder.append("El nombre no puede contener números ni caracteres especiales\n");
            isValidForm = false;
        }
        
        //apellido
        String apellido = apellidoTextField.getText();
        if(StringUtils.isBlank(apellido.trim())){
            errorMessageBuilder.append("El apellido no puede estar vacío\n");
            isValidForm = false;
        }
        if(!StringUtils.isAlphaSpace(apellido)){
            errorMessageBuilder.append("El apellido no puede contener números ni caracteres especiales\n");
            isValidForm = false;
        }
        
        //promedio
        String promedio = promedioTextField.getText().trim();
        if(StringUtils.isBlank(promedio)){
            errorMessageBuilder.append("El promedio no puede estar vacío\n");
            isValidForm = false;
        } else {
            try {
                double prom = Double.parseDouble(promedio.replace(",", "."));
                if(prom < 0 || prom > 10){
                    errorMessageBuilder.append("El promedio debe estar entre 0 y 10\n");
                    isValidForm = false;
                }
            } catch (NumberFormatException e) {
                errorMessageBuilder.append("El promedio debe ser un número\n");
                isValidForm = false;
            }
        }

        //cantidad materias aprobadas
        String cantMat = cantMatAprobTextField.getText().trim();
        if(StringUtils.isBlank(cantMat)){
            errorMessageBuilder.append("La cantidad de materias aprobadas no puede estar vacía\n");
            isValidForm = false;
        } else if(!StringUtils.isNumeric(cantMat)){
            errorMessageBuilder.append("La cantidad de materias aprobadas debe ser un número entero\n");
            isValidForm = false;
        }

        //fecha nacimiento
        Calendar fecNacCalendar = fecNacDateChooser.getCalendar();
        if(fecNacCalendar == null){
            errorMessageBuilder.append("La fecha de nacimiento no puede estar vacía\n");
            isValidForm = false;
        } else if(fecNacCalendar.after(Calendar.getInstance())){
            errorMessageBuilder.append("La fecha de nacimiento no puede ser posterior al día actual\n");
            isValidForm = false;
        }

        //fecha ingreso
        Calendar calendar = fecIngDateChooser.getCalendar();
        if(calendar != null){
            if(calendar.after(Calendar.getInstance())){
                errorMessageBuilder.append("La fecha de ingreso no puede ser posterior al día actual\n");
                isValidForm = false;
            }
            if(!calendar.isSet(Calendar.DAY_OF_MONTH)){
                errorMessageBuilder.append("La fecha de ingreso debe contener un día\n");
                isValidForm = false;
            }
            if(!calendar.isSet(Calendar.MONTH)){
                errorMessageBuilder.append("La fecha de ingreso debe contener un mes\n");
                isValidForm = false;
            }
            if(!calendar.isSet(Calendar.YEAR)){
                errorMessageBuilder.append("La fecha de ingreso debe contener un año\n");
                isValidForm = false;
            }

            Calendar fecIngMinima = (Calendar) fecNacCalendar.clone();
            fecIngMinima.add(Calendar.YEAR, 18);
            if (calendar.before(fecIngMinima)) {
                errorMessageBuilder.append("La fecha de ingreso debe ser al menos 18 años posterior a la fecha de nacimiento\n");
                isValidForm = false;
            }
        } else {
            errorMessageBuilder.append("La fecha de ingreso no puede estar vacía\n");
            isValidForm = false;
        }
        
        
        if(!isValidForm)
            JOptionPane.showMessageDialog(this, errorMessageBuilder.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        
        return isValidForm;
    }
}
